import SessionProvider from '@/components/SessionProvider'
import '../styles/globals.css'
import Sidebar from "@/components/Sidebar/Sidebar"
import { getServerSession } from "next-auth"
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Chat GPT Next',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session=await getServerSession(authOptions)
  return (
    <html lang="en">
      <SessionProvider session={session}>
      <body>
        <div className="grid grid-cols-12 h-[100%]">
          <div className="col-span-2">
            <Sidebar/>
          </div>
          <div className="col-span-10">

        {children}
          </div>
        </div>
        </body>
        </SessionProvider>
    </html>
  )
}
