import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LeftBar from './LeftBar/LeftBar'
import RightBar from './RightBar/RightBar'
import NewChat from './components/NewChat'
import ChatTitle from './components/ChatTitle'
import IconButton from './components/IconButton'
import { useEffect, useState } from 'react'
import HomePage from './HomePage/HomePage'
import Sidebar from './components/Sidebar/Sidebar'
import Main from './Main/Main'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [prompt, setPrompt] = useState("");
  const [response, setResponse] = useState("");
  const data = {
    prompt
  }
  // useEffect(() => {
  //   fetch("/api/Backend", {
  //     method: "POST",
  //     headers: {
  //       "Content-Type": "application/json"
  //     },
  //     body: JSON.stringify(data)
  //   }).then(res => res.json())
  //     .then(data => console.log(data)).catch(err => console.log(err))
  // }, [prompt])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="overflow-hidden w-full h-full relative flex">
        <div className="dark hidden bg-gray-900 md:flex md:w-[260px] md:flex-col">
          <div className="flex h-full min-h-0 flex-col ">
            <div className="scrollbar-trigger flex h-full w-full flex-1 items-start border-white/20">
              <nav className="flex h-full flex-1 flex-col space-y-1 p-2">
                <LeftBar/>
              </nav>
            </div>
          </div>
        </div>
        <RightBar setPrompt={setPrompt} prompt={prompt} response={response}/>
      </div> */}
      <div className="grid grid-cols-12">
        <div className="col-span-2">
          <div className="bg-[#202123] max-w-xs overflow-y-auto md:min-w-[20rem]">
            <Sidebar />
          </div>
        </div>
        <div className="bg-[#343541] col-span-10">
          <HomePage />
        </div>
      </div>
    </>
  )
}
